# Generated by Django 4.0.6 on 2022-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcase',
            name='description',
        ),
        migrations.AddField(
            model_name='showcase',
            name='description_mobile',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='showcase',
            name='description_web',
            field=models.TextField(null=True),
        ),
    ]
