# Generated by Django 4.0.6 on 2022-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_whatwedo_delete_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
