# Generated by Django 4.0.6 on 2022-07-09 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_fivestudent_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(default='five-students/default.jpg', null=True, upload_to='five-students/')),
                ('description', models.TextField(blank=True, null=True)),
                ('social_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('social_github', models.CharField(blank=True, max_length=500, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('social_snapchat', models.CharField(blank=True, max_length=500, null=True)),
                ('social_website', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FiveStudent',
        ),
    ]
