# Generated by Django 4.0.6 on 2022-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_moderator_delete_fivestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
