# Generated by Django 4.0.6 on 2022-07-10 15:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_moderator_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
