# Generated by Django 4.0.6 on 2022-07-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_moderator_social_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='social_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
