# Generated by Django 4.0.6 on 2022-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_moderator_social_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='social_email',
            field=models.URLField(blank=True, null=True),
        ),
    ]
