# Generated by Django 4.0.6 on 2022-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_moderator_social_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='featured_image',
            field=models.ImageField(default='moderators/default.jpg', null=True, upload_to='moderators/'),
        ),
    ]
