# Generated by Django 4.0.6 on 2022-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_moderator_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='moderator',
            name='featured_image',
            field=models.ImageField(default='images/moderators/default.jpg', null=True, upload_to='images/moderators/'),
        ),
    ]
