# Generated by Django 4.0.6 on 2022-07-17 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_about_alter_moderator_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
