# Generated by Django 4.0.6 on 2022-07-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_about_featured_video_alter_about_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='caption',
        ),
    ]
