# Generated by Django 4.0.6 on 2022-07-27 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('utc_date', models.CharField(blank=True, max_length=200)),
                ('featured_map', models.ImageField(null=True, upload_to='images/maps/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryForecast',
            fields=[
                ('utc_date', models.CharField(max_length=200)),
                ('temperature_day', models.IntegerField()),
                ('temperature_night', models.IntegerField()),
                ('rain_day', models.CharField(max_length=255)),
                ('rain_night', models.CharField(max_length=255)),
                ('probability_day', models.IntegerField()),
                ('probability_night', models.IntegerField()),
                ('relative_humidy_day', models.IntegerField()),
                ('relative_humidy_night', models.IntegerField()),
                ('wind_from_day', models.CharField(max_length=255)),
                ('wind_from_night', models.CharField(max_length=255)),
                ('wind_speed_day', models.IntegerField()),
                ('wind_speed_night', models.IntegerField()),
                ('wind_gust_day', models.IntegerField()),
                ('wind_gust_night', models.IntegerField()),
                ('sunset', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sunrise', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('maps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecasts.map')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureAndRelativeHumidity',
            fields=[
                ('utc_date', models.CharField(blank=True, max_length=200)),
                ('featured_graph', models.ImageField(null=True, upload_to='images/graphs/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('maps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecasts.map')),
                ('summary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecasts.summaryforecast')),
            ],
        ),
        migrations.AddField(
            model_name='summaryforecast',
            name='temp_rh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecasts.temperatureandrelativehumidity'),
        ),
        migrations.AddField(
            model_name='map',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecasts.summaryforecast'),
        ),
        migrations.AddField(
            model_name='map',
            name='temp_rh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecasts.temperatureandrelativehumidity'),
        ),
    ]
