# Generated by Django 4.0.6 on 2022-07-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryforecast',
            name='maps',
        ),
        migrations.RemoveField(
            model_name='summaryforecast',
            name='temp_rh',
        ),
        migrations.RemoveField(
            model_name='temperatureandrelativehumidity',
            name='maps',
        ),
    ]
